import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MySideBar from "@/layout/Sidebar/MySideBar";
import { ActiveProvider } from "@/layout/Sidebar/ActiveContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ActiveProvider>
      <html lang="en">
        <body className={`inter.className flex`}>
          <MySideBar />
          {children}
        </body>
      </html>
    </ActiveProvider>
  );
}
